# LDS: 0.1862

steps:
  - magic:
      run_path: runs/gpt2_wikitext_dropout
      model: gpt2
      overwrite: true
      cleanup_ckpts: false
      train_mode: true
      weight_decay: 0.01
      adam_eps: 1.0e-8
      eps_root: 1.0e-6
      loss_reduction: mean

      data:
        dataset: EleutherAI/bergson-wikitext-512-chunks
        split: "train"
        chunk_length: 0

      query:
        dataset: EleutherAI/bergson-wikitext-512-chunks
        split: "test[0:1]"
        chunk_length: 0

      distributed:
        nproc_per_node: 8
        nnode: 1

      batch_size: 64
      num_epochs: 4
      lr_schedule:
        lr_scheduler_type: polynomial
        lr: 0.0008
        lr_start: 1e-6
        lr_end: 0.00008
        warmup_steps: 0.25

      wandb_project: magic
      save_optimizer_state: True
      save_retrained_models: True
